### ISSUE TITLE
[Suggestion] option to make pipes behave like snakes

### ISSUE THREAD

**Issue by Swedneck** [pipeseroni/pipes.sh#36]
I feel just clearing the terminal looks kind of jarring, it'd be cool if you could make the ends of pipes disappear as they reach the -r limit.

**Comment by Foggalong** [comment]
That's an interesting idea; the idea comes from how the Pipes screensaver worked on Windows XP but that's definitely something we could look to add as an optional flag

**Comment by livibetter** [comment]
Indeed an interesting idea, but I don't think it's feasible in terms of performance.

IIRC, the current implementation (or recent, if it has been changed), the script only keeps the heads of pipes, their position, direction, and colors. The performance is already not good, it's in Bash, so expected.

That being said, all this script does is piping a pipe forward, basically, that's all.

If you want to make it like Snakes/Nibbles, first, it would have to go through a significant rewrite as the data structure (/me chuckles) isn't there to support to keep the whole length of a pipe.  It is doable, but currently only looping through heads of pipes, the script will have to redraw the entire length of each pipe.

You need to redraw all, because when one pipe crawls forward, you add a new head and remove the tail, then erase the tail on screen.  Sounds simple right, and it is.  However, when with other pipes and considering a pipe can piping over itself, the tail could be on top/bottom of other pipes, redrawing all is one way to deal with it, the simplest way.

The performance is going to get a significant hit, if not devastating.  And frankly, I could definitely bet that being without any attempt of optimization on the simplest implementation (simply redrawing all pipes) might be the fastest implementation.

You can try to give each pipe their own map/layer with time tag assigned to each pipe piece, then composite all into one with respect to the time tags of pieces, then diff against previous entire screen output, so you optimize the amount of outputs.  Yeah, right.  No chance it, in Bash, would run faster than redrawing all in my mind.

From my experiences with Bash, after avoiding externals, there isn't really much you could optimize for performance of Bash execution, in fact, it quite often slows down, the more lines you add for performance, more likely slower as more lines to parse, to expand, to evaluate, and to bash down the performance, so to speak.

The redrawing all in terminal might be much faster than Bash execution.

To simply put it, Bash isn't for such task, wrong language for this nice feature, but you can still do it, because you can.  I'd love see someone does it, like Snake game in Sed and in Bash, yes, they are real, some people did that.

I would recommend moving this feature request onto [C][] (1) or anything other than Bash version, they can do optimizations and actually get the performance boost.

[C]: https://github.com/pipeseroni/Snakes
(1): I'd love to see the C version's functionality (features / command-line options) matches up to this Bash version.

**Comment by livibetter** [comment]
@Foggalong could you label this as Enhancement and Help Wanted, although I would just close it as Won't Fix since it's unlikely we will get a patch (it'd be big) regardless the performance issue I mentioned above.

**Comment by livibetter** [comment]
I will be closing this as wontfix in about 30 days, because I can't see any possibility of this ever being implemented.  At this moment, this is at stage for comments.  If they demonstrate any chances, I will leave this open.

**Comment by livibetter** [comment]
I think I finally realized what @Swedneck meant by snakes, it is like [maze.py][maze], but still recording the whole length.  If we try for maze.py, we only one 2D array to mark if there is a section of snake.  Still would take a lot of work.

[maze]: https://github.com/pipeseroni/maze.py

And more works, if we want the snake to crawl forward, and clearing the tail.  Anyway, I am still going to close this.

**Comment by livibetter** [comment]
Per my previous comment, closing, but if someone implement this in the future, please do open a PR; or ask for reopen, if necessary.
